In [1]:
import pandas as pd

In [38]:
Customers= pd.read_csv('customers.csv')
Orders= pd.read_parquet('orders.parquet')
url = "https://raw.githubusercontent.com/MohammedHameds/test1455/refs/heads/main/products.csv"
Products = pd.read_csv(url)

## Extraction

In [17]:
Customers

   customer_id first_name last_name        city  age            email
0            1      Ahmed    Hassan       Cairo   25  ahmed@email.com
1            2       Sara       Ali        Giza   31   sara@email.com
2            3       Omar   Mohamed       cairo   17   omar@email.com
3            4       Mona   Ibrahim  Alexandria   28              NaN
4            5      Ahmed    Hassan       Cairo   25  ahmed@email.com

In [18]:
Customers.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   customer_id  5 non-null      int64
 1   first_name   5 non-null      str
 2   last_name    5 non-null      str
 3   city         5 non-null      str
 4   age          5 non-null      int64
 5   email        4 non-null      str
dtypes: int64(2), str(4)
memory usage: 511.0 bytes

In [19]:
Customers['email']= Customers['email'].fillna('no email')

In [6]:
print(Customers["email"])

0    ahmed@email.com
1     sara@email.com
2     omar@email.com
3           no email
4    ahmed@email.com
Name: email, dtype: str

In [7]:
Customers.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   customer_id  5 non-null      int64
 1   first_name   5 non-null      str
 2   last_name    5 non-null      str
 3   city         5 non-null      str
 4   age          5 non-null      int64
 5   email        5 non-null      str
dtypes: int64(2), str(4)
memory usage: 518.0 bytes

In [20]:
Customers['city']

0         Cairo
1          Giza
2         cairo
3    Alexandria
4         Cairo
Name: city, dtype: str

In [21]:
Customers['city'] = Customers["city"].str.strip().str.title()

In [22]:
Customers['Full_Name'] = Customers['first_name'] + ' ' + Customers['last_name']

In [23]:
print(Customers["age"].unique())

[25 31 17 28]

In [26]:
Customers = Customers.drop_duplicates(subset=['customer_id'], keep='first')

In [29]:
print(Customers.duplicated().sum())

0

In [27]:
Customers

,customer_id,first_name,last_name,city,age,email,Full_Name
0,1,Ahmed,Hassan,Cairo,25,ahmed@email.com,Ahmed Hassan
1,2,Sara,Ali,Giza,31,sara@email.com,Sara Ali
2,3,Omar,Mohamed,Cairo,17,omar@email.com,Omar Mohamed
3,4,Mona,Ibrahim,Alexandria,28,no email,Mona Ibrahim
4,5,Ahmed,Hassan,Cairo,25,ahmed@email.com,Ahmed Hassan

In [39]:
Orders

    order_id  customer_id  product_id  quantity order_date
0       1001            1         101         2 2026-09-01
1       1002            2         102         1 2026-09-01
2       1003            3         103         3 2026-09-02
3       1004            4         101         1 2026-09-02
4       1005            1         104         2 2026-09-03
5       1006            5         102         1 2026-09-03
6       1007            2         105         4 2026-09-04
7       1008            3         101         1 2026-09-04
8       1009            4         103         2 2026-09-05
9       1010            1         104         1 2026-09-05
10      1003            3         103         3 2026-09-02

In [40]:
Orders.info()

<class 'pandas.DataFrame'>
RangeIndex: 11 entries, 0 to 10
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   order_id     11 non-null     int64
 1   customer_id  11 non-null     int64
 2   product_id   11 non-null     int64
 3   quantity     11 non-null     int64
 4   order_date   11 non-null     datetime64[us]
dtypes: datetime64[us](1), int64(4)
memory usage: 572.0 bytes

In [41]:
print(Orders.duplicated().sum())

1

In [42]:
Orders = Orders.drop_duplicates(subset=['order_id'], keep='first')

In [43]:
print(Orders.duplicated().sum())

0

In [44]:
print(Orders["quantity"].unique())

[2 1 3 4]

In [45]:
print(Orders["customer_id"].unique())

[1 2 3 4 5]

In [49]:
Products

   product_id product_name     category  unit_price
0         101       Laptop  Electronics       25000
1         102        Mouse  Accessories         500
2         103     Keyboard  Accessories        1200
3         104      Monitor  Electronics        7000
4         105   Headphones  Accessories        2500
5         106       Webcam  Accessories        1800

In [50]:
Products.info()

<class 'pandas.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   product_id    6 non-null      int64
 1   product_name  6 non-null      str
 2   category      6 non-null      str
 3   unit_price    6 non-null      int64
dtypes: int64(2), str(2)
memory usage: 432.0 bytes

In [52]:
Products['product_name'] = Products["product_name"].str.strip().str.title()

In [53]:
Products['product_name'] = Products["category"].str.strip().str.title()

In [54]:
print(Products["unit_price"].unique())

[25000   500  1200  7000  2500  1800]

In [56]:
Products = Products.drop_duplicates(subset=['product_id'], keep='first')

In [57]:
Customers

   customer_id first_name last_name        city  age            email
0            1      Ahmed    Hassan       Cairo   25  ahmed@email.com
1            2       Sara       Ali        Giza   31   sara@email.com
2            3       Omar   Mohamed       cairo   17   omar@email.com
3            4       Mona   Ibrahim  Alexandria   28              NaN
4            5      Ahmed    Hassan       Cairo   25  ahmed@email.com

In [58]:
Products

   product_id product_name     category  unit_price
0         101  Electronics  Electronics       25000
1         102  Accessories  Accessories         500
2         103  Accessories  Accessories        1200
3         104  Electronics  Electronics        7000
4         105  Accessories  Accessories        2500
5         106  Accessories  Accessories        1800

In [ ]:
Orders

   order_id  customer_id  product_id  quantity order_date
0      1001            1         101         2 2026-09-01
1      1002            2         102         1 2026-09-01
2      1003            3         103         3 2026-09-02
3      1004            4         101         1 2026-09-02
4      1005            1         104         2 2026-09-03
5      1006            5         102         1 2026-09-03
6      1007            2         105         4 2026-09-04
7      1008            3         101         1 2026-09-04
8      1009            4         103         2 2026-09-05
9      1010            1         104         1 2026-09-05

In [ ]:
#join orders and customers with customer_id
#join orders and products with product_id

In [60]:
Sales = pd.merge(Orders, Customers, on='customer_id', how='left')
Sales = pd.merge(Sales, Products, on='product_id', how='left')

In [61]:
Sales["total_amount"] = Sales["quantity"] * Sales["unit_price"]

In [62]:
Sales

,order_id,customer_id,product_id,quantity,order_date,first_name,last_name,city,age,email,product_name,category,unit_price,total_amount
0,1001,1,101,2,2026-09-01,Ahmed,Hassan,Cairo,25,ahmed@email.com,Electronics,Electronics,25000,50000
1,1002,2,102,1,2026-09-01,Sara,Ali,Giza,31,sara@email.com,Accessories,Accessories,500,500
2,1003,3,103,3,2026-09-02,Omar,Mohamed,cairo,17,omar@email.com,Accessories,Accessories,1200,3600
3,1004,4,101,1,2026-09-02,Mona,Ibrahim,Alexandria,28,NaN,Electronics,Electronics,25000,25000
4,1005,1,104,2,2026-09-03,Ahmed,Hassan,Cairo,25,ahmed@email.com,Electronics,Electronics,7000,14000
5,1006,5,102,1,2026-09-03,Ahmed,Hassan,Cairo,25,ahmed@email.com,Accessories,Accessories,500,500
6,1007,2,105,4,2026-09-04,Sara,Ali,Giza,31,sara@email.com,Accessories,Accessories,2500,10000
7,1008,3,101,1,2026-09-04,Omar,Mohamed,cairo,17,omar@email.com,Electronics,Electronics,25000,25000
8,1009,4,103,2,2026-09-05,Mona,Ibrahim,Alexandria,28,NaN,Accessories,Accessories,1200,2400
9,1010,1,104,1,2026-09-05,Ahmed,Hassan,Cairo,25,ahmed@email.com,Electronics,Electronics,7000,7000

In [66]:
Sales = Sales.rename(columns={ 
    'customer_id': 'Customer',
    'product_id': 'Product',
    'quantity': 'Quantity',
})

In [71]:
drop_columns = ['order_date', 'first_name','last_name', 'category', 'city', 'email', 'age']
Sales = Sales.drop(columns=drop_columns, errors="ignore")

In [72]:
Sales

,order_id,Customer,Product,Quantity,product_name,unit_price,total_amount
0,1001,1,101,2,Electronics,25000,50000
1,1002,2,102,1,Accessories,500,500
2,1003,3,103,3,Accessories,1200,3600
3,1004,4,101,1,Electronics,25000,25000
4,1005,1,104,2,Electronics,7000,14000
5,1006,5,102,1,Accessories,500,500
6,1007,2,105,4,Accessories,2500,10000
7,1008,3,101,1,Electronics,25000,25000
8,1009,4,103,2,Accessories,1200,2400
9,1010,1,104,1,Electronics,7000,7000

## Load to SQL server

In [77]:
import pyodbc

conn = pyodbc.connect('Driver={ODBC Driver 17 for SQL Server};'
                        'Server=depi12462.database.windows.net;'  
                        'Database=free-sql-db-1400982;'
                        'UID=sqladmin;'
                        'PWD=Depi123#'
                        )   

cursor = conn.cursor()

In [78]:
sql_query = """
create table Jana_Sales(
    OrderId int,
    Customer int,
    Product int,
    Quantity int,
    Product_name varchar(50),
    unit_price float,
    total_amount float
)
"""

cursor.execute(sql_query)
conn.commit()

In [79]:
insert_sql = """
INSERT INTO Jana_Sales (OrderId, Customer, Product, Quantity, Product_name, unit_price, total_amount)
VALUES (?,?,?,?,?,?,?)
"""

In [80]:
print(Sales.columns.tolist())

['order_id', 'Customer', 'Product', 'Quantity', 'product_name', 'unit_price', 'total_amount']

In [81]:
cursor.executemany(insert_sql, Sales[['order_id', 'Customer', 'Product', 'Quantity', 'product_name', 'unit_price', 'total_amount']].values.tolist())
conn.commit()

## Flask Dashboard

In [91]:
from flask import Flask, render_template, jsonify
import pandas as pd
from sqlalchemy import create_engine
from urllib.parse import quote_plus

app = Flask(__name__)

conn_str = (
    "Driver={ODBC Driver 17 for SQL Server};"
    "Server=depi12462.database.windows.net;"
    "Database=free-sql-db-1400982;"
    "UID=sqladmin;"
    "PWD=Depi123#"
)
engine = create_engine("mssql+pyodbc:///?odbc_connect=" + quote_plus(conn_str))

def get_sales():
    return pd.read_sql("SELECT * FROM Jana_Sales", engine)

@app.route('/')
def dashboard():
    df = get_sales()
    return render_template(
        'dashboard.html',
        columns=df.columns.tolist(),
        rows=df.values.tolist(),
        total_revenue=round(df['total_amount'].sum(), 2),
        total_orders=len(df),
    )

@app.route('/api/sales')
def sales_json():
    return jsonify(get_sales().to_dict(orient='records'))

if __name__ == '__main__':
    app.run(port=5001, use_reloader=False)

 * Serving Flask app '__main__'
 * Debug mode: off

WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on http://127.0.0.1:5001
Press CTRL+C to quit
127.0.0.1 - - [05/Oct/2026 18:42:29] "GET / HTTP/1.1" 200 -